CREATE DATABASE pern;

CREATE TABLE todo(
	todo_id SERIAL PRIMARY KEY,
	description VARCHAR(255)
);

CREATE TABLE H_Business(
	ID SERIAL PRIMARY KEY,
	CompanyID VARCHAR(255),
	BusinessName VARCHAR(255),
	Address VARCHAR(255), 
	Email VARCHAR(255), 
	PhoneNumber VARCHAR(255),
	CreatedDate DATE
);

CREATE TABLE H_Agent(
	ID SERIAL PRIMARY KEY,
	Business SERIAL,
	Image TEXT,
	Position TEXT,
	Rating SMALLINT,
	Products VARCHAR(255),
	Customer VARCHAR(255),
	Email VARCHAR(255),
	PhoneNumber VARCHAR(255),
	CONSTRAINT FK_BUSINESS FOREIGN KEY(Business) REFERENCES H_Business(ID)
); 

CREATE TYPE CATEGORY_TYPE AS ENUM ('cat1', 'cat2', 'cat3');

CREATE TABLE S_Task(
	ID SERIAL PRIMARY KEY,
	Agent_ID SERIAL,
	CATEGORY CATEGORY_TYPE,
	TIMETOCOMPLETE TIMESTAMP,
	CREATEDDATE TIMESTAMP,
	CONSTRAINT FK_AGENT FOREIGN KEY(Agent_ID) REFERENCES H_Agent(ID)
);