CREATE DATABASE pern;

-- !! START ENUM !!
-- category_type
CREATE TYPE public.category_type AS ENUM
    ('cat1', 'cat2', 'cat3');

-- gender
CREATE TYPE public.gender AS ENUM
    ('Male', 'Female');

-- status task
CREATE TYPE public.task_status AS ENUM
    ('Done', 'In Progress', 'Pending', 'Not Started');

-- !! END ENUM !!

-- !! START TABLES !!

-- h_agent
CREATE TABLE IF NOT EXISTS public.h_agent
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    business integer NOT NULL DEFAULT nextval('h_agent_business_seq'::regclass),
    image text COLLATE pg_catalog."default",
    "position" text COLLATE pg_catalog."default",
    rating smallint,
    email character varying(255) COLLATE pg_catalog."default",
    phonenumber character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT h_agent_pkey PRIMARY KEY (id),
    CONSTRAINT fk_business FOREIGN KEY (business)
        REFERENCES public.h_business (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

-- h_business
CREATE TABLE IF NOT EXISTS public.h_business
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    companyid character varying(255) COLLATE pg_catalog."default",
    businessname character varying(255) COLLATE pg_catalog."default",
    address character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    phonenumber character varying(255) COLLATE pg_catalog."default",
    createddate date,
    CONSTRAINT h_business_pkey PRIMARY KEY (id)
)

-- h_customer
CREATE TABLE IF NOT EXISTS public.h_customer
(
    "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying(255) COLLATE pg_catalog."default",
    "Gender" gender,
    "Agent" integer NOT NULL DEFAULT nextval('"h_customer_Agent_seq"'::regclass),
    "Email" character varying(255) COLLATE pg_catalog."default",
    "PhoneNumber" character varying(255) COLLATE pg_catalog."default",
    "Address" character varying(255) COLLATE pg_catalog."default",
    "ShippingAddress" character varying(255) COLLATE pg_catalog."default",
    "Recurring" boolean,
    "CreatedDate" timestamp without time zone,
    "IC" character varying(255) COLLATE pg_catalog."default",
    "Preference" character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT h_customer_pkey PRIMARY KEY ("ID"),
    CONSTRAINT "CustomerToAgent" FOREIGN KEY ("Agent")
        REFERENCES public.h_agent (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

-- h_product
CREATE TABLE IF NOT EXISTS public.h_product
(
    "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Name" character varying COLLATE pg_catalog."default",
    "Price" character varying(255) COLLATE pg_catalog."default",
    "Description" character varying(255) COLLATE pg_catalog."default",
    "Stock" integer,
    "Agent" integer NOT NULL DEFAULT nextval('"h_product_Agent_seq"'::regclass),
    "Business" integer NOT NULL DEFAULT nextval('"h_product_Business_seq"'::regclass),
    "Type" character varying COLLATE pg_catalog."default",
    "SKU" character varying(255) COLLATE pg_catalog."default",
    "Image" text COLLATE pg_catalog."default",
    CONSTRAINT h_product_pkey PRIMARY KEY ("ID"),
    CONSTRAINT "ProductToAgent" FOREIGN KEY ("Agent")
        REFERENCES public.h_agent (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "ProductToBusiness" FOREIGN KEY ("Business")
        REFERENCES public.h_business (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

-- l_agent_customer
CREATE TABLE IF NOT EXISTS public."l_Agent_Customer"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    agentid integer NOT NULL,
    customerid integer NOT NULL,
    "createdDate" timestamp with time zone NOT NULL,
    CONSTRAINT fk_agent FOREIGN KEY (agentid)
        REFERENCES public.h_agent (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT fk_customer FOREIGN KEY (customerid)
        REFERENCES public.h_customer ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

-- l_agent_product
CREATE TABLE IF NOT EXISTS public.l_agent_product
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    agentid integer NOT NULL,
    productid integer NOT NULL,
    "createdDate" timestamp with time zone,
    CONSTRAINT l_agent_product_pkey PRIMARY KEY (id),
    CONSTRAINT fk_agentid FOREIGN KEY (id)
        REFERENCES public.h_agent (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_productid FOREIGN KEY (id)
        REFERENCES public.h_product ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

--  l_customer_product
CREATE TABLE IF NOT EXISTS public.l_customer_product
(
    "ID" integer NOT NULL DEFAULT nextval('"l_customer_product_ID_seq"'::regclass),
    "Customer" integer NOT NULL DEFAULT nextval('"l_customer_product_Customer_seq"'::regclass),
    "Product" integer NOT NULL DEFAULT nextval('"l_customer_product_Product_seq"'::regclass),
    "CreatedDate" timestamp without time zone,
    CONSTRAINT l_customer_product_pkey PRIMARY KEY ("ID"),
    CONSTRAINT "CustomerFK" FOREIGN KEY ("Customer")
        REFERENCES public.h_customer ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "ProductFK" FOREIGN KEY ("Product")
        REFERENCES public.h_product ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

-- s_lead
CREATE TABLE IF NOT EXISTS public.s_lead
(
    "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Agent" integer NOT NULL DEFAULT nextval('"s_lead_Agent_seq"'::regclass),
    "ProductInterest" integer NOT NULL DEFAULT nextval('"s_lead_ProductInterest_seq"'::regclass),
    "Customer" integer NOT NULL DEFAULT nextval('"s_lead_Customer_seq"'::regclass),
    "Contact" character varying(255) COLLATE pg_catalog."default",
    "Followup" timestamp without time zone,
    "EngagementChannel" character varying COLLATE pg_catalog."default",
    "CreatedDate" timestamp without time zone,
    CONSTRAINT s_lead_pkey PRIMARY KEY ("ID"),
    CONSTRAINT "LeadToAgent" FOREIGN KEY ("Agent")
        REFERENCES public.h_agent (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "LeadToCustomer" FOREIGN KEY ("Customer")
        REFERENCES public.h_customer ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "LeadToProduct" FOREIGN KEY ("ProductInterest")
        REFERENCES public.h_product ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

-- s_sales
CREATE TABLE IF NOT EXISTS public.s_sales
(
    "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Agent" integer NOT NULL DEFAULT nextval('"s_sales_Agent_seq"'::regclass),
    "Customer" integer NOT NULL DEFAULT nextval('"s_sales_Customer_seq"'::regclass),
    "DeliveryCost" character varying COLLATE pg_catalog."default",
    "TotalPrice" character varying COLLATE pg_catalog."default",
    "Products" json,
    "CreatedDate" timestamp without time zone,
    CONSTRAINT s_sales_pkey PRIMARY KEY ("ID"),
    CONSTRAINT "SalesToAgent" FOREIGN KEY ("Agent")
        REFERENCES public.h_agent (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT "SalesToCustomer" FOREIGN KEY ("Customer")
        REFERENCES public.h_customer ("ID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)

-- s_task
CREATE TABLE IF NOT EXISTS public.s_task
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    agent_id integer NOT NULL DEFAULT nextval('s_task_agent_id_seq'::regclass),
    category category_type,
    timetocomplete timestamp without time zone,
    createddate timestamp without time zone,
    title character varying(255) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    status task_status,
    CONSTRAINT s_task_pkey PRIMARY KEY (id),
    CONSTRAINT fk_agent FOREIGN KEY (agent_id)
        REFERENCES public.h_agent (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)



-- !! END TABLES !!